/**
* 열심히해보자
* 뭐지
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models

import io.swagger.server.models.Writer

/**
 * 
 * @param id 
 * @param title 
 * @param content 
 * @param writer 
 * @param createdAt 
 */
data class AnnouncementResponse (

    val id: java.math.BigDecimal? = null,
    val title: kotlin.String? = null,
    val content: kotlin.String? = null,
    val writer: Writer? = null,
    val createdAt: java.time.LocalDateTime? = null
) {
}
