/**
* 열심히해보자
* 뭐지
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 * 
 * @param id 
 * @param name 
 */
data class Writer (

    val id: java.math.BigDecimal? = null,
    val name: kotlin.String? = null
) {
}
